name: Capture

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Environment
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - uses: actions/checkout@v2
    - run: yarn && yarn build

    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Move assets
      run: rm -rf assets/ index.html && mv dist/index.html . && mv dist/assets .

    - name: Publish
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Bot
        author_email: i.zzetao@gmail.com
        message: "Publish page"
        add: "."
